name: dispatch src updated
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  dispatch-target-updated:
    name: dispatch-alg-src-updated
    runs-on: ubuntu-latest
    steps:
    - name: start
      run: echo "dispatch src updated event"
    - name: src dispatch event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.SRC_SYNC_KEY }}
        repository: GrykT/Actions2
        event-type: a-src-updated
    - name: end
      run: echo "done"
      